name: Github Actions Test

on:
  push:
    branches: ["master", "Development"]
  pull_request:
    branches: ["master", "Development"]
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run test
        run: npm run test:ci
        